### ISSUE TITLE
['22/01/31~'22/02/06] 정희석 TODO

### ISSUE THREAD

**Issue by dev-heeseok** [dev-heeseok/tutorial#2]
# 2월 1주차 할일목록

## 쉽고 빠르게 배우는 파이썬 GUI 프로그래밍 수강

- [x] 제1절 파이썬 GUI Programming & widget
- [x] 제2절 widget의 배치 & 꾸미기
- [x] 제3절 widget3(다이얼로그와 메뉴의 표현 외)
- [x] 제4절 제어변수 활용하기
- [x] 제5절 widget 처리 고급기법
- [x] 제6절 파일데이터 위젯에 적재하기

**Comment by dev-heeseok** [comment]
1~6 절 온라인 강의 수강 완료
