### ISSUE TITLE
['22/02/07~'22/02/13] 정희석 TODO

### ISSUE THREAD

**Issue by dev-heeseok** [dev-heeseok/tutorial#3]
# 2월 2주차 할일목록

## 쉽고 빠르게 배우는 파이썬 GUI 프로그래밍 수강

- [x] 제7절 이벤트 핸들링(Ⅰ)
- [x] 제8절 이벤트 핸들링(Ⅱ)
- [x] 제9절 키보드 ＆ 마우스 이벤트
- [x] 제10절 Mini project
- [x] 제11절 데이터분석도구 pandas와 DataFrame
- [x] 제12절 pandas DataFrame(II) ＆ GUI 연동
- [x] 제13절 DataFrame ＆ plotting 결과 GUI 연동하기

**Comment by dev-heeseok** [comment]
2월 2주차 일정 완료
